
ALTER TABLE branches ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS instagram TEXT;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS city TEXT DEFAULT 'Rosario';
ALTER TABLE branches ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;
