-- Lo de Granados core schema (mirrors SQLite / TypeORM entities)
-- Source: backend/data/lodegranados.db schema dump

CREATE TABLE IF NOT EXISTS public.branch (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  address text,
  city text,
  "zipCode" text,
  phone text,
  instagram text,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.plan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  emoji text NOT NULL,
  price numeric NOT NULL,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  highlighted boolean NOT NULL DEFAULT false,
  badge text,
  "imageUrl" text
);

CREATE TABLE IF NOT EXISTS public."user" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  password text,
  "googleId" text UNIQUE,
  name text NOT NULL,
  role text NOT NULL DEFAULT 'member',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_role_check CHECK (role IN ('member', 'admin', 'superadmin'))
);

CREATE TABLE IF NOT EXISTS public.user_branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
  branch_id bigint NOT NULL REFERENCES public.branch(id) ON DELETE CASCADE,
  "assignedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.branch_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id bigint NOT NULL REFERENCES public.branch(id) ON DELETE CASCADE,
  plan_id bigint NOT NULL REFERENCES public.plan(id) ON DELETE CASCADE,
  UNIQUE (branch_id, plan_id)
);

CREATE TABLE IF NOT EXISTS public.event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  date text NOT NULL,
  time text NOT NULL,
  location text NOT NULL,
  "totalSpots" integer NOT NULL DEFAULT 20,
  "availableSpots" integer NOT NULL DEFAULT 20,
  active boolean NOT NULL DEFAULT true,
  price numeric NOT NULL DEFAULT 5000,
  branch_id bigint REFERENCES public.branch(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.course (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  "instructorName" text NOT NULL,
  "instructorBio" text NOT NULL,
  "totalClasses" integer NOT NULL,
  "startDate" text NOT NULL,
  schedule text NOT NULL,
  syllabus jsonb NOT NULL DEFAULT '[]'::jsonb,
  "totalSpots" integer NOT NULL DEFAULT 20,
  "availableSpots" integer NOT NULL DEFAULT 20,
  active boolean NOT NULL DEFAULT true,
  price numeric NOT NULL DEFAULT 8000,
  branch_id bigint REFERENCES public.branch(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.event_registration (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  "eventId" bigint NOT NULL,
  spots integer NOT NULL DEFAULT 1,
  attended boolean NOT NULL DEFAULT false,
  "registeredAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.course_enrollment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  "courseId" bigint NOT NULL,
  status text NOT NULL DEFAULT 'enrolled',
  "enrolledAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT course_enrollment_status_check CHECK (status IN ('enrolled', 'completed', 'dropped'))
);

CREATE TABLE IF NOT EXISTS public.subscription (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  "planId" bigint NOT NULL,
  status text NOT NULL DEFAULT 'active',
  "monthlyPrice" numeric NOT NULL,
  "startDate" text NOT NULL,
  notes text,
  "mpPreapprovalId" text,
  "mpPaymentId" text,
  "mpPayerId" text,
  "mpSubscriptionStatus" text,
  branch_id bigint REFERENCES public.branch(id) ON DELETE SET NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inquiry (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  message text NOT NULL,
  branch_id bigint REFERENCES public.branch(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'new',
  reply text,
  "repliedAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.newsletter (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.password_reset (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  token text NOT NULL UNIQUE,
  "expiresAt" timestamptz NOT NULL,
  used boolean NOT NULL DEFAULT false,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.payment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mpPaymentId" text,
  "mpPreapprovalId" text,
  type text NOT NULL,
  "itemId" bigint NOT NULL,
  "externalReference" text NOT NULL,
  amount numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  "payerEmail" text NOT NULL,
  "payerName" text,
  branch_id bigint,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_event_branch_id ON public.event(branch_id);
CREATE INDEX IF NOT EXISTS idx_course_branch_id ON public.course(branch_id);
CREATE INDEX IF NOT EXISTS idx_event_registration_event_id ON public.event_registration("eventId");
CREATE INDEX IF NOT EXISTS idx_event_registration_email ON public.event_registration(email);
CREATE INDEX IF NOT EXISTS idx_course_enrollment_course_id ON public.course_enrollment("courseId");
CREATE INDEX IF NOT EXISTS idx_payment_external_reference ON public.payment("externalReference");
CREATE INDEX IF NOT EXISTS idx_payment_mp_payment_id ON public.payment("mpPaymentId");
CREATE INDEX IF NOT EXISTS idx_subscription_mp_preapproval ON public.subscription("mpPreapprovalId");
CREATE INDEX IF NOT EXISTS idx_user_branches_user_id ON public.user_branches(user_id);
CREATE INDEX IF NOT EXISTS idx_user_branches_branch_id ON public.user_branches(branch_id);
