
DROP TABLE IF EXISTS user_branches CASCADE;
DROP TABLE IF EXISTS branch_plans CASCADE;
DROP TABLE IF EXISTS course_enrollment CASCADE;
DROP TABLE IF EXISTS event_registration CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS password_reset CASCADE;
DROP TABLE IF EXISTS subscription CASCADE;
DROP TABLE IF EXISTS inquiry CASCADE;
DROP TABLE IF EXISTS newsletter CASCADE;
DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS plan CASCADE;
DROP TABLE IF EXISTS branch CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
