BEGIN;
SET session_replication_role = replica;
-- branch_plans: 42 rows
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (1, 22, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (2, 22, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (3, 11, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (4, 11, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (5, 15, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (6, 15, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (7, 25, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (8, 25, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (9, 16, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (10, 16, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (11, 17, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (12, 17, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (13, 20, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (14, 20, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (15, 9, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (16, 9, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (17, 8, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (18, 8, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (19, 21, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (20, 21, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (21, 28, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (22, 28, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (23, 13, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (24, 13, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (25, 27, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (26, 27, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (27, 26, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (28, 26, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (29, 14, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (30, 14, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (31, 18, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (32, 18, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (33, 19, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (34, 19, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (35, 24, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (36, 24, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (37, 23, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (38, 23, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (39, 10, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (40, 10, 3);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (41, 12, 2);
INSERT INTO public.branch_plans (id, branch_id, plan_id) OVERRIDING SYSTEM VALUE VALUES (42, 12, 3);
SET session_replication_role = DEFAULT;
COMMIT;
